[build]
    base = "client"
    publish = "client/dist" # what folder to publish 
    command = "npm run build" # how to trigger a build
    

[[redirects]]
    from = "/*" # redirect any path
    to = "/public/index.html" # to this html page
    status = 200 # with this status